name: Telugu BabyLM Workflow

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  run-babylm-project:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3

    - name: 🐍 Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: 🔧 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert notebook ipykernel matplotlib pandas torch transformers

    - name: 📘 Run Sentence Scoring Notebook
      run: |
        jupyter nbconvert --to notebook --execute Sentence_Scoring.ipynb --inplace

    - name: 🤖 Run Telugu BabyLM Model Notebook
      run: |
        jupyter nbconvert --to notebook --execute BabyLM_Telugu_model.ipynb --inplace

    - name: ✅ Done
      run: echo "All notebooks executed successfully!"
